### ISSUE TITLE
Dependency to ACS AEM Commons not explicitly marked

### ISSUE THREAD

**Issue by joerghoh** [Adobe-Marketing-Cloud/asset-share-commons#29]
When ACS AEM Commons is not deployed on the AEM instance, it might result in exceptions like this:

```
28.10.2017 20:53:34.777 *WARN* [0:0:0:0:0:0:0:1 [1509216814763] GET /content/asset-share-commons/en/light/actions/cart.partial.html HTTP/1.1] com.adobe.aem.commons.asset
share.core [com.adobe.aem.commons.assetshare.components.actions.share.impl.EmailShareServiceImpl(3202)] Failure loooking up field assetDetailsResolver in class class com
.adobe.aem.commons.assetshare.components.actions.share.impl.EmailShareServiceImpl. Assuming no such field. (java.lang.NoClassDefFoundError: Lcom/adobe/acs/commons/email/
EmailService;)
java.lang.NoClassDefFoundError: Lcom/adobe/acs/commons/email/EmailService;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredField(Class.java:2068)
        at org.apache.felix.scr.impl.inject.FieldHandler.getField(FieldHandler.java:222)
        at org.apache.felix.scr.impl.inject.FieldHandler.findField(FieldHandler.java:159)
        at org.apache.felix.scr.impl.inject.FieldHandler.access$400(FieldHandler.java:51)
        at org.apache.felix.scr.impl.inject.FieldHandler$NotResolved.resolve(FieldHandler.java:838)
        at org.apache.felix.scr.impl.inject.FieldHandler$NotResolved.fieldExists(FieldHandler.java:864)
        at org.apache.felix.scr.impl.inject.FieldHandler.fieldExists(FieldHandler.java:918)
        at org.apache.felix.scr.impl.inject.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:982)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2201)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1118)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1520)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1006)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:859)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)
        at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:347)
        at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:247)
        at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:344)
        at org.apache.felix.framework.Felix.getService(Felix.java:3700)
        at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:470)
        at org.apache.sling.models.impl.injectors.OSGiServiceInjector.getService(OSGiServiceInjector.java:104)
        at org.apache.sling.models.impl.injectors.OSGiServiceInjector.getValue(OSGiServiceInjector.java:157)
```

Asset Share should not work if this dependency is not fulfilled, rather than just throwing this exception.

**Comment by davidjgonzalez** [comment]
@joerghoh the commons depend upon is optional.  Everything should work except the email sharing without commons.

**Comment by davidjgonzalez** [comment]
@joerghoh ah - i read the exception on my computer (vs phone ;)) and agree there's an  issue; if the sharing is not enabled (ie. ACS Commons is not installed) then there shouldnt be calls into the Email service (IIRC access into the ACS Commons code for sharing is proxied vis the Share Service; if there is not registered Share service, then no other sharing code should be in the execution path)

**Comment by justinedelson** [comment]
@davidjgonzalez Based on my experience with the twitter bundle in ACS AEM Commons, this is going to be tricky. It might actually make more sense to invert the relationship -- put the EmailShareServiceImpl in ACS AEM Commons (with an option import of asset share there).

**Comment by davidjgonzalez** [comment]
@joerghoh how did you get this exception to happen? Do you recall the steps to reproduce?

The Share button shouldnt be active unless Sharing is enabled, which in turn is only available when there is atleast 1 Share Service active.

**Comment by joerghoh** [comment]
I don't remember. I think I just played around with it.

**Comment by davidjgonzalez** [comment]
Closed via #86
