### ISSUE TITLE
Asset share commons - cart click gives issue

### ISSUE THREAD

**Issue by akaash2512** [Adobe-Marketing-Cloud/asset-share-commons#299]
Hi All,

We have extended ASC pages and created our own pages under our hierarchy.

But we get below error.

```
org.apache.sling.models.factory.PostConstructException: Post-construct method has thrown an exception for model class com.adobe.aem.commons.assetshare.content.impl.AssetModelImpl
	at org.apache.sling.models.impl.ModelAdapterFactory.createObject(ModelAdapterFactory.java:705)
	at org.apache.sling.models.impl.ModelAdapterFactory.internalCreateModel(ModelAdapterFactory.java:394)
	at org.apache.sling.models.impl.ModelAdapterFactory.getAdapter(ModelAdapterFactory.java:249)
	at org.apache.sling.adapter.internal.AdapterManagerImpl.getAdapter(AdapterManagerImpl.java:147)
	at org.apache.sling.engine.impl.SlingMainServlet.adaptTo(SlingMainServlet.java:591)
	at org.apache.sling.engine.impl.request.RequestData.adaptTo(RequestData.java:658)
	at org.apache.sling.engine.impl.SlingHttpServletRequestImpl.adaptTo(SlingHttpServletRequestImpl.java:89)
	at org.apache.sling.api.wrappers.SlingHttpServletRequestWrapper.adaptTo(SlingHttpServletRequestWrapper.java:148)
	at org.apache.sling.api.wrappers.SlingHttpServletRequestWrapper.adaptTo(SlingHttpServletRequestWrapper.java:148)
	at org.apache.sling.api.wrappers.SlingHttpServletRequestWrapper.adaptTo(SlingHttpServletRequestWrapper.java:148)
	at org.apache.sling.api.wrappers.SlingHttpServletRequestWrapper.adaptTo(SlingHttpServletRequestWrapper.java:148)
	at org.apache.sling.api.wrappers.SlingHttpServletRequestWrapper.adaptTo(SlingHttpServletRequestWrapper.java:148)
	at org.apache.sling.api.wrappers.SlingHttpServletRequestWrapper.adaptTo(SlingHttpServletRequestWrapper.java:148)
	at com.adobe.aem.commons.assetshare.util.impl.ModelCacheImpl.get(ModelCacheImpl.java:53)
	at com.adobe.aem.commons.assetshare.util.impl.ModelCacheImpl.get(ModelCacheImpl.java:41)
	at org.apache.sling.scripting.sightly.compiler.util.ObjectModel.resolveProperty(ObjectModel.java:117)
	at org.apache.sling.scripting.sightly.render.AbstractRuntimeObjectModel.getProperty(AbstractRuntimeObjectModel.java:148)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.SlingRuntimeObjectModel.getProperty(SlingRuntimeObjectModel.java:32)
	at org.apache.sling.scripting.sightly.render.AbstractRuntimeObjectModel.resolveProperty(AbstractRuntimeObjectModel.java:84)
	at org.apache.sling.scripting.sightly.apps.dcx__002d__customerportal__002d__dam.components.details.action__002d__buttons.action__002d__buttons_html.render(action__002d__buttons_html.java:53)
	at org.apache.sling.scripting.sightly.java.compiler.RenderUnit.render(RenderUnit.java:48)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyCompiledScript.eval(SightlyCompiledScript.java:61)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:386)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
	at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilterWithErrorHandling(WCMDebugFilter.java:192)
	at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:159)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.core.impl.WCMComponentFilter.doFilter(WCMComponentFilter.java:278)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.wcm.core.impl.PageLockFilter.doFilter(PageLockFilter.java:91)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at com.day.cq.personalization.impl.TargetComponentFilter.doFilter(TargetComponentFilter.java:96)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.dispatchRequest(SlingRequestProcessorImpl.java:322)
	at org.apache.sling.engine.impl.request.SlingRequestDispatcher.dispatch(SlingRequestDispatcher.java:211)
	at org.apache.sling.engine.impl.request.SlingRequestDispatcher.include(SlingRequestDispatcher.java:104)
	at com.day.cq.wcm.core.impl.WCMComponentFilter$ForwardRequestDispatcher.include(WCMComponentFilter.java:516)
	at com.adobe.cq.sightly.WCMScriptHelper.includeResource(WCMScriptHelper.java:179)
	at com.adobe.cq.sightly.internal.extensions.ResourceExtension.call(ResourceExtension.java:139)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.call(RenderContextImpl.java:69)
	at org.apache.sling.scripting.sightly.libs.wcm.foundation.components.responsivegrid.responsivegrid_html.render(responsivegrid_html.java:113)
	at org.apache.sling.scripting.sightly.java.compiler.RenderUnit.render(RenderUnit.java:48)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyCompiledScript.eval(SightlyCompiledScript.java:61)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:386)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
```

Regards,
Akash B.

**Comment by davidjgonzalez** [comment]
Is the actual Exception thats thrown in the PostConstruct available?

It appears this is happening on the Asset Details page, specifically on the Actions Button component. 

1) If you remove the Actions Button component from the page, does teverything work for that same Asset?
2) Is there anything interesting/unusual about the Asset? (Ie. if you inspect it in CRXDE Lite, does it have a metadata node? jcr:content/renditons, etc?

**Comment by davidjgonzalez** [comment]
@akaash2512 bump - could review and answer my questions in the comment above? Thanks!

**Comment by akaash2512** [comment]
Hi David,

It is happening on asset search results page.

Not reproducible on vanilla pages.

Regards,
Akash B.

**Comment by davidjgonzalez** [comment]
@akaash2512 sorry - im asking if it happens on a vanilla AEM + the ASC ui.apps and ui.content (without any custom code/extension for ASC)..

**Comment by davidjgonzalez** [comment]
Please feel free to reopen with the info from my last comment (confirming this is an issue with Vanilla ASC)

**Comment by clovan** [comment]
Error Message:

org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/wknd/components/content/byline/byline_html.java:
Line 28, column 1272 : Only a type can be imported. com.adobe.aem.guides.wknd.core.components.Byline resolves to a package
Line 43, column 1858 : Byline cannot be resolved to a typ

**Comment by davidjgonzalez** [comment]
@clovan what version of ASC are you running? Have you installed/followed the WKND tutorial on this aem instance?
