### ISSUE TITLE
ASC filter issue

### ISSUE THREAD

**Issue by Sayali-Kolhatkar** [Adobe-Marketing-Cloud/asset-share-commons#559]
We are using asset-share-commons 1.8.0 packages and we have created customized filters.

We have used properties component for creating filters. Earlier we have given Equals operation on one of the filter later we changed it to property exists. To get exact results, we changed it to Equals but now after applying filters we are getting 500 in network tab after.

Please find below error log.

    **org.apache.sling.scripting.sightly.SightlyException: org.apache.sling.api.scripting.ScriptEvaluationException:** 
	at com.adobe.cq.sightly.WCMScriptHelper.includeResource(WCMScriptHelper.java:184)
	at com.adobe.cq.sightly.internal.extensions.ResourceExtension.call(ResourceExtension.java:138)
	at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.call(RenderContextImpl.java:77)
	at **org.apache.sling.scripting.sightly.apps.asset__002d__share__002d__commons.components.structure.page.results_html.render(results_html.java:39)**
	
	Caused by: org.apache.sling.api.scripting.ScriptEvaluationException: 
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:416)
	
	**Caused by: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: Operands are not of the same type: comparison is supported for Number types only.**
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:510)
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552)
	
	**Caused by: org.apache.sling.scripting.sightly.compiler.SightlyCompilerException: Operands are not of the same type: comparison is supported for Number types only.
	at org.apache.sling.scripting.sightly.compiler.expression.nodes.BinaryOperator.leq(BinaryOperator.java:214)
	at org.apache.sling.scripting.sightly.apps.asset__002d__share__002d__commons.components.search.results.result.card.card_html.render(card_html.java:106)**
	at org.apache.sling.scripting.sightly.render.RenderUnit.render(RenderUnit.java:50)
	at org.apache.sling.scripting.sightly.impl.engine.SightlyCompiledScript.eval(SightlyCompiledScript.java:60)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:386)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184)
	at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491)

Any guidance/help will be appreciated. Thanks in advance!

**Comment by shijuc18** [comment]
Same issue as above, an immediate help would be really appreciated.

**Comment by Sayali-Kolhatkar** [comment]
Any guidance/help will be really appreciated as this is a critical issue for us. Thanks in advance!

**Comment by davidjgonzalez** [comment]
@Sayali-Kolhatkar  @shijuc18 - are you both on 1.8.0? Any chance you can try with the latest 1.9.x version?

**Comment by shijuc18** [comment]
@davidjgonzalez - I am in 1.8.0 David. Yes, we can try 1.9.0. Is there a fix made to 1.9.0 for the above issue ?

**Comment by davidjgonzalez** [comment]
@shijuc18 I am having trouble re-producing this on 1.8.0.
Are you able to re-produce this on a lower environment? If so, can you:

1.  install ACS Tools [1]
2. Goto Tools > ACS AEM Tools > JSP Code Display
3. Paste in`org.apache.sling.scripting.sightly.apps.asset__002d__share__002d__commons.components.search.results.result.card.card_html.render(card_html.java:106)` and  paste in the resultant output.. 

Mine looks like this for example:

![image](https://user-images.githubusercontent.com/1451868/102804061-3859fe80-4387-11eb-937c-728054304f48.png)

This will give us exactly what in the HTL is failing ... I assume? its the same line as mine - but am hoping this could give us some hints...


[1]  https://github.com/Adobe-Consulting-Services/acs-aem-tools/releases/download/acs-aem-tools-1.0.2/acs-aem-tools-content-1.0.2-min.zip

**Comment by shijuc18** [comment]
Please see attached.

![image](https://user-images.githubusercontent.com/76411801/102805158-cedaef80-4388-11eb-99eb-8506da3dbbf0.png)

**Comment by shijuc18** [comment]
This is what I could see in the environment where we are facing issue

**Comment by davidjgonzalez** [comment]
@shijuc18  can you copy/paste that full line in to the comments?

**Comment by davidjgonzalez** [comment]
Can you also add debug statements to your card.html and see what the values are for that results size object?

![image](https://user-images.githubusercontent.com/1451868/102805904-ef577980-4389-11eb-8c2b-831a61dde709.png)

**Comment by shijuc18** [comment]
@davidjgonzalez - When executed with the error @Sayali-Kolhatkar  was getting , which is 'org.apache.sling.scripting.sightly.apps.asset__002d__share__002d__commons.components.structure.page.results_html.render(results_html.java:39)' , I got below line. 

    Object var_resourcecontent0 = renderContext.call("includeResource", "root/main/responsivegrid", obj().with("wcmmode", "disabled").with("resourceType", "foundation/components/parsys"));

![image](https://user-images.githubusercontent.com/76411801/102805829-cb943380-4389-11eb-96a4-f5e3b6c4fc8a.png)


For the line 'org.apache.sling.scripting.sightly.compiler.expression.nodes.BinaryOperator.leq(BinaryOperator.java:214)' , got the response that compiled JSP not found.


![image](https://user-images.githubusercontent.com/76411801/102806023-1f068180-438a-11eb-9e9d-d5922b3001df.png)

**Comment by davidjgonzalez** [comment]
You want to check `org.apache.sling.scripting.sightly.apps.asset__002d__share__002d__commons.components.search.results.result.card.card_html.render(card_html.java:106)` as that is what was the root cause of the exception for you per your stack trace above - obviously if youve changed those JSPs while debugging - youll need to retrigger the error and use the updated line #.  But it looks like its the same as my line 106 anyhow - which is checking is `search.results.size > 0` ... try dropping in debug statements into the `card.html` as noted in the post above, and see if they are in null or not.

**Comment by shijuc18** [comment]
@davidjgonzalez  - C
[CompleteLog.txt](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/5725763/CompleteLog.txt)
omplete log after debug statement attached.

**Comment by davidjgonzalez** [comment]
I think you'll need to disable Error Handler... as that rewrites the page. We're specifically trying to see what those 3 values are. 
You can disable Error Page Handler by going to

/system/console/configMgr > ACS AEM Commons Error Page Handler > Unchecking "Enable" .. 

Then refresh the page - you need to make sure you can see those 3 lines output.

Alternatively, you could always hook up a remote debugger to your AEM and step through (but that's probably a bit more involved).

**Comment by davidjgonzalez** [comment]
Also, probably should've asked this first - are there any other errors/warns in the `error.log` other than the stack trace you're seeing on the page?

**Comment by shijuc18** [comment]
@davidjgonzalez  results are not null when this error comes, please see below

![image](https://user-images.githubusercontent.com/76411801/102812132-888b8d80-4394-11eb-8e6a-d0379256cfc1.png)

**Comment by davidjgonzalez** [comment]
@shijuc18 very strange -- the size appears to be a number, so i'm not sure why its complaining ...  Can you add the following beneath those inline debug outputs?

```
<br/>
Test if size is a number: ${'#,###.00' @ format=search.results.size}
```

These should help us determine if HTL thinks the size is coming back as a Number of a String. If its indeed a number, it should print out `24.00` and if its a string, the should not print anything out.

Also..
1. Have you made a custom Results implementation by any chance? (or overridden anything in the Search/Results java classes?)
2. Do you have this problem on the vanilla ASC demo page? Can you configure the ASC demo page to break in this way (if so, what exactly do you change)?

**Comment by shijuc18** [comment]
@davidjgonzalez  - Please see what is printed out

![image](https://user-images.githubusercontent.com/76411801/102825097-1cb51f00-43ac-11eb-831f-d3ff2876a5f8.png)

We haven't made any customizations except the custom filters. Nothing was overriden in results or java classes

**Comment by davidjgonzalez** [comment]
Ok - this is very strange .. since it's formatting as if we're a number. Can you provide a txt file of the entire jsp code display output for that erroring card.html?

**Comment by Sayali-Kolhatkar** [comment]
@davidjgonzalez 
PFA complete card.html jsp code display after searching for org.apache.sling.scripting.sightly.apps.asset__002d__share__002d__commons.components.search.results.result.card.card_html.render(card_html.java:106)
[card_html.txt](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/5728567/card_html.txt)

**Comment by davidjgonzalez** [comment]
@Sayali-Kolhatkar what version of AEM + SP are you on?

**Comment by davidjgonzalez** [comment]
Can you try:

[asset-share-commons.ui.apps-1.9.5-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/5730722/asset-share-commons.ui.apps-1.9.5-SNAPSHOT.zip)

This pulls the `${search.results.size > 0}` check into the Sling Model as a `hasResults()` method

**Comment by Sayali-Kolhatkar** [comment]
We are using AEM 6.5.2.0 and we have 6.1.SP2, 6.3.2.zip, 6.5.2.zip installed.
We have tried asset-share-commons.ui.apps-1.9.5-SNAPSHOT.zip as mentioned above with 1.9.4 content package but we were getting blank page as below rather than the expected result after applying the issue causing filter.
Is there any configuration change which might cause this issue? 

![image](https://user-images.githubusercontent.com/58510275/102993904-09d55280-4544-11eb-872a-84afdbe2828a.png)

**Comment by davidjgonzalez** [comment]
I assume there's an error being thrown? What's the error?

It certainly seems like something strange is going on on your AEM deployment, as I cannot reproduce any of this behavior. :(

**Comment by shijuc18** [comment]
@davidjgonzalez - Any configMgr configuration need to be checked for this ?

**Comment by Sayali-Kolhatkar** [comment]
@davidjgonzalez 
There were no such errors, we were getting 200 for resulting url but no results were displaying. After clicking on that url we can see all content of light page except expected results.

Is there any particular dispatcher setting or configMgr configuration need to be checked?
